{
  "hash": "57a54b395fefc192260f0b5534c481f8",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Lab Eight -- Probability # Title of the document\n\n# Bibliography Details\nbibliography: Lab8References.bib  # Name of bib file in the same folder \nbibliographystyle: apa            # Bibliography style\n\nexecute:               # Default settings for code blocks\n  warning: false       # Do not print warnings\n  message: false       # Do not print messages\n  size: \"scriptsize\"   # Set code size to script size\n\n# Below will do html by default. To render the entire project\n# Use the following code:\n# quarto::quarto_render(\"Lab8WriteUp.qmd\")\nformat:\n  pdf:        # Specify .pdf formatting options \n    documentclass: article     # Document Class\n    number-sections: true      # Number Sections\n    reference-section-title: \"References\" # Title for reference section\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables \n    geometry:\n      - top=0.75in\n      - left=0.75in\n      - bottom=0.75in\n      - right=0.75in\n  html:       # Specify HTML formatting options \n    number-sections: true      # Number Sections\n    code-fold: true            # Button to show code\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables and figures\nformat-links: [pdf]\n---\n\n \\normalsize\n\n\n::: {.cell}\n\n:::\n\n\n \\normalsize\n\n\n\n**Tips**\n\n* Complete the tasks below. Make sure to start your solutions in on a new line that starts with \"**Solution**:\".\n* Make sure to use the Quarto Cheatsheet. This will make completing and writing up the lab *much* easier.\n* Make sure to use \"enter\" to make your code readable, so it doesn't run off the page. I switched the Quarto document to automatically render to .pdf, so you can see what you're submitting by default. You can switch back for the highlighting by moving the html block above the pdf block in the YAML header.\n* Don't forget that you can copy-and-paste code when you're doing something similar as we did in class!\n* Make sure to plot all computed probabilities. This is good `ggplot` practice AND will help make sure you don't make a mistake when computing the probability.\n\n# The Binomial and Negative Binomial Distributions\n\n## The Binomial Distribution\nIn many introductory courses, we make the simplifying assumption of independence in Bernoulli trials. For example, when playing best two-out-of-three legs in a darts match, we would assume Player A has an 70% chance of winning each leg. We write:\n$$X \\sim \\text{Binomial}(n=3, p=0.70)$$\nwhere\n\n* $X$ is the number of legs won\n* $n$ is the number of trials \n* $p$ is the probability of the event of interest\n\nOf note, it is not necessarily the case that the players play all three legs -- if either player wins legs one and two the match ends.\n\nThere are eight possible outcomes for Player A:\n\n* (win, win, \"win\") $\\longrightarrow$ Player A wins\n* (win, win, \"lose\") $\\longrightarrow$ Player A wins\n* (win, lose, win) $\\longrightarrow$ Player A wins\n* (win, lose, lose) $\\longrightarrow$ Player A loses\n* (lose, win, win)  $\\longrightarrow$ Player A wins\n* (lose, win, lose) $\\longrightarrow$ Player A loses\n* (lose, lose, \"win\") $\\longrightarrow$ Player A loses\n* (lose, lose, \"lose\") $\\longrightarrow$ Player A loses\n\n**Note**: I use quotations above to denote outcomes where the last match isn't actually played.\n\n**Use the Binomial distribution to compute the probability that Player A wins the match.  Make sure write out your probability statement and work to write it in terms of the distribution function (PMF/CDF) to plot the probability using `ggplot`.**\n\n**Solution**\n\nHere, I am looking for $P(X\\geq2)$, the probability that player A wins at least two matches. I can do \n\\begin{align*}\nP(X \\geq 2) &= 1 - P(X<2)\\\\\n&= 1 - P(X\\leq1)\\\\\n&= 1 - F_X(1)\\\\\n\\end{align*}\n\nThus, I can use the CDF function (pbinom) to easily calculate this probability. I've also plotted both CDF and PMF below, highlighting the probability we were calculating for. \n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nwin_percent = 1 - pbinom(q=1, prob = 0.7, size = 3)\n(win_percent)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.784\n```\n\n\n:::\n\n```{.r .cell-code}\nggdat = tibble(x = 0:3) |>\n  mutate(PMF = dbinom(x=x, prob=0.7, size = 3),\n        CDF = pbinom(q=x, prob = 0.7, size = 3))\n\nPMF.plot = ggplot() +\n  geom_linerange(data = ggdat,\n                aes(x = x, ymin = 0, ymax = PMF)) +\n  geom_linerange(data = ggdat |> filter(x>=2),\n                aes(x = x, ymin = 0, ymax = PMF),\n                color = \"darkorchid2\", linewidth=2, alpha=0.5) +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"x\", breaks=0:4) +\n  ylab(\"Probability\") +\n  theme_bw()\n\nCDF.plot = ggplot() +\n  geom_step(data=ggdat, aes(x = x, y = CDF)) +\n  geom_point(data=ggdat |> filter(x==1), \n            aes(x = x, y = CDF),\n            color=\"darkorchid2\", size = 2.5, alpha =0.5) +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"x\", breaks=0:4) +\n  ylab(\"Cumulative Probability\") +\n  theme_bw()\n\nPMF.plot | CDF.plot\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-pdf/unnamed-chunk-2-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n\n## The Negative Binomial Distribution\nIn intermediate courses, we learn the Negative Binomial distribution that we use to model the number of \"failures\" until the $r$th success. Note that this approach still makes the simplifying assumption of independence in Bernoulli trials.\n\n**Specify the two cases necessary to compute the probability. Fully explain these probability statements in the context of a best two-out-of-three match and the Negative Binomial distribution. Finally, compute the probability that Player A wins the match and show you get the same result as the Binomial approach. Make sure write out your probability statement and work to write it in terms of the distribution function (PMF/CDF) to plot the probability using `ggplot`.**\n\n**Solution**\n\nThere are two cases for the two out of three match. The first case is player A wins the first two matches in a row, and technically wins immediately. The second case is player A has exactly one loss before their two wins in order to win the whole game. Therefore, let X be the number of failures before Player A gets two wins. So, the probability that player A wins, where X follows a negative binomial distribution, is $P(X\\leq1)$. \n\n\n$$P(X \\leq 1) = F_X(1)$$\n\n\n\nI get the same result as I did for the binomial distribution. \n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nwin_percent = pnbinom(q=1, prob=0.7, size = 2)\n(win_percent)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.784\n```\n\n\n:::\n\n```{.r .cell-code}\nggdat = tibble(x = 0:5) |>\n  mutate(PMF = dnbinom(x=x, prob=0.7, size = 2),\n        CDF = pnbinom(q=x, prob = 0.7, size = 2))\n\nPMF.plot = ggplot() +\n  geom_linerange(data = ggdat,\n                aes(x = x, ymin = 0, ymax = PMF)) +\n  geom_linerange(data = ggdat |> filter(x<=1),\n                aes(x = x, ymin = 0, ymax = PMF),\n                color = \"darkorchid2\", linewidth=2, alpha=0.5) +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"Number of Failures (x)\", breaks=0:5) +\n  ylab(\"Probability\") +\n  theme_bw()\n\nCDF.plot = ggplot() +\n  geom_step(data=ggdat, aes(x = x, y = CDF)) +\n  geom_point(data=ggdat |> filter(x==1), \n            aes(x = x, y = CDF),\n            color=\"darkorchid2\", size = 2.5, alpha =0.5) +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"Number of Failures (x)\", breaks=0:5) +\n  ylab(\"Cumulative Probability\") +\n  theme_bw()\n\nPMF.plot | CDF.plot\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-pdf/unnamed-chunk-3-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n# The Beta Binomial Distribution\nOne approach to generalize this modeling is to use a Beta-Binomial distribution. This distribution arrises when we let $p$ be a random variable that follows a Beta distribution:\n\\begin{align*}\n  P &\\sim \\text{Beta}(\\alpha, \\beta)\\\\\n  X &\\sim \\text{Binomial}(n, P).\n\\end{align*}\nThis distribution is not part of base `R`, but is available using the `_bbinom` functions from the `extraDistr` package [@extraDistr].\n\nThe primary benefit is that the Beta-Binomial enables us to specify some uncertainty about the skill of Player A, as $p$ does not have to be fixed (e.g., $p=0.70$). Suppose the result of the best two-out-of-three match follows a Beta-Binomial distribution  where $\\alpha=7$ and $\\beta=3$.\n\n## The Beta Part\n1. **Plot the corresponding Beta distribution. Interpret the plot in the context of a best two-out-of-three match and the Binomial distribution.**\\\n**Hint**: The Beta distribution is available in base `R` via `_beta()`.\n\n**Solution**\n\nThe distribution models the uncertainty of Player A's leg-win probability. Instead of it being a fixed value at 0.7, the distribution is centered around 0.7 with some variance such that the leg-win probability could be slightly above or below that. \n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nggdat = tibble(x = seq(0, 1, length.out=1000)) |>\n  mutate(PDF = dbeta(x = x, 7, 3),\n        CDF = pbeta(q = x, 7, 3))\n\nPDF.plot = ggplot(ggdat) +\n  geom_line(aes(x = x, y = PDF)) +\n  geom_hline(yintercept = 0) +\n  xlab(\"x\") +\n  ylab(\"Density\") +\n  theme_bw()\n\nCDF.plot = ggplot(ggdat) +\n  geom_line(aes(x = x, y = CDF)) +\n  geom_hline(yintercept = 0) +\n  xlab(\"x\") +\n  ylab(\"Cumulative Probability\") +\n  theme_bw()\n\nPDF.plot | CDF.plot\n```\n\n::: {.cell-output-display}\n![Beta Distribution](Lab8WriteUp_files/figure-pdf/unnamed-chunk-4-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n1. How does the Beta incorporate uncertainty about the skill of Player A? **Compute the mean and variance of the distribution.**\\\n**Hint**: You will find the `integrate(...)` function helpful here. \n\\begin{align*}\n  E(P) &= \\mu_P = \\int_{0}^1 p f_P(p) dp\\\\\n  var(P) &= \\sigma^2_P = \\int_{0}^1 (p-\\mu_P)^2 f_P(p) dp\\\\\n\\end{align*}\n\n**Solution**\n\nThe Beta incorporates uncertianty through the variance of the distribution which slightly varies the skill of Player A. \nI make separate functions for each mean and variance, and then I integrate each from 0 to 1. I had an issue here because I didn't realize the integrate function returns characters so I had to specify my value using value. \n\n \\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#mean\nf_mean = function(p){\n  p * dbeta(p, 7, 3)\n}\n#beta mean\nbeta_mean = integrate(f_mean, lower = 0, upper = 1)\n(beta_mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.7 with absolute error < 7.8e-15\n```\n\n\n:::\n\n```{.r .cell-code}\n#var\nf_var = function(p){\n  dbeta(p,7,3) * (p-beta_mean$value)^2\n}\n#beta var\nbeta_var = integrate(f_var, lower = 0, upper = 1)\n(beta_var)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.01909091 with absolute error < 2.1e-16\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n1. **What is the probability that Player A has a win probability of exactly 0.70?  Make sure to write out your probability statement and work to write it in terms of the distribution function (PDF/CDF) to plot the probability using `ggplot`.**\\\n**Hint:** Think carefully about the properties of continuous distributions here.\n\n**Solution**\n\nBecause X is a continuous random variable on a Beta distribution, the probability of any exact single value is 0. Density is not the same thing as probability here. \n\n1. **What is the probability that Player A has a win probability of at least 0.50?  Make sure write out your probability statement and work to write it in terms of the distribution function (PDF/CDF) to plot the probability using `ggplot`.**\n\n**Solution**\n\n$$P(X\\geq0.5) = 1-P(X\\leq0.5) = 1-F_X(0.5)$$\n\nI use a standard probability statement to find I just need to use the CDF function to find this probability. I shade the region on the density graph and mark the point on the CDF plot. \n\n\n \\normalsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\n#atleast 50 win prob\nprob_0.5 = 1 - pbeta(q = 0.5, shape1 = 7, shape2 = 3)\nprob_0.5\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9101562\n```\n\n\n:::\n\n```{.r .cell-code}\nggdat = tibble(x = seq(0, 1, length.out = 1000)) |>\n  mutate(\n    PDF = dbeta(x = x, 7, 3),\n    CDF = pbeta(q = x, 7, 3)\n  )\n\nPDF.plot = ggplot() +\n  geom_line(data=ggdat,aes(x = x, y = PDF), \n                  alpha = 0.3) +\n  geom_ribbon(data=ggdat |> filter(x >=0.5),\n                aes(x = x, ymin = 0, ymax = PDF),\n                fill = \"darkorchid2\", alpha=0.5) +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"x\", breaks=seq(0,1,by=0.2)) +\n  ylab(\"Density\") +\n  theme_bw()\n\nCDF.plot = ggplot() +\n  geom_line(data = ggdat, aes(x = x, y = CDF)) +\n  geom_point(data = ggdat |> filter(x==1), \n            aes(x = 0.5, y = pbeta(q=0.5,7,3)),\n            color=\"darkorchid2\", size = 2.5, alpha =0.5) +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"x\", breaks=seq(0,1,by=0.2)) +\n  ylab(\"Cumulative Probability\") +\n  theme_bw()\n\nPDF.plot | CDF.plot\n```\n\n::: {.cell-output-display}\n![At least 50% win probability](Lab8WriteUp_files/figure-pdf/atleast50-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n1. **What is the 90th percentile of Player A's win probability based on this Beta distribution? Make sure write out your probability statement and work to write it in terms of the distribution function (PDF/CDF) to plot the percentile using `ggplot`.**\n\n\n**Solution**\n\nFor the 90th percentile I set up as:\n\n$$P(X\\leq q) = 0.90 = F_X(q)$$\n\nSolving for q: \n$$q = F_X^{-1}(0.90)$$\n\nWe can easily use the inverse CDF function for this. \n\n\n \\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#90th percentile win prob\nq_90 = qbeta(p = 0.90, shape1 = 7, shape2 = 3)\nq_90\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8705027\n```\n\n\n:::\n\n```{.r .cell-code}\nggdat = tibble(x = seq(0, 1, length.out = 1000)) |>\n  mutate(\n    PDF = dbeta(x = x, 7, 3),\n    CDF = pbeta(q = x, 7, 3)\n  )\n\nPDF.plot = ggplot() +\n  geom_line(data = ggdat,\n                 aes(x = x, y = PDF)) +\n  geom_ribbon(data = ggdat |> filter(x <= q_90),\n                 aes(x = x, ymin = 0, ymax = PDF),\n                 fill = \"darkorchid2\", alpha = 0.5) +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"x\", breaks = seq(0, 1, by = 0.2)) +\n  ylab(\"Density\") +\n  theme_bw()\n\nCDF.plot = ggplot() +\n  geom_line(data = ggdat, aes(x = x, y = CDF)) +\n  geom_point(aes(x = q_90, y = 0.90),\n             color = \"darkorchid2\", size = 2.5, alpha = 0.5) +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"x\", breaks = seq(0, 1, by = 0.2)) +\n  ylab(\"Cumulative Probability\") +\n  theme_bw()\n\nPDF.plot | CDF.plot\n```\n\n::: {.cell-output-display}\n![90th percent](Lab8WriteUp_files/figure-pdf/unnamed-chunk-6-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n\n## The Beta-Binomial Part\n**Compute the probability that Player A wins the match. Compare your result to the Binomial and Negative Binomial results. Make sure write out your probability statement and work to write it in terms of the distribution function (PMF/CDF) to plot the probability using `ggplot`**\n\n**Solution**\n\nFor X being the number of legs won by Player A in the game, under the beta-binomial model, X follows the beta-bionomial distribution. Player A wins if they win at least 2 out of the 3 legs. Thus,\n\n$$P(X\\geq 2) = 1 - P(X\\leq 1) = 1 - F_X(1)$$\n\nThis is similar to the binomial model, but now our leg winning probability varies slightly accoridng to the beta distribution. \n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#our varying win prob\nwin = 1 - pbbinom(q = 1, size = 3, alpha = 7, beta = 3)\nwin\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7636364\n```\n\n\n:::\n\n```{.r .cell-code}\nggdat = tibble(x = 0:3) |>\n  mutate(\n    PMF = dbbinom(x = x, size = 3, alpha = 7, beta = 3),\n    CDF = pbbinom(q = x, size = 3, alpha = 7, beta = 3)\n  )\n\nPMF.plot = ggplot() +\n  geom_linerange(data = ggdat,\n                 aes(x = x, ymin = 0, ymax = PMF)) +\n  geom_linerange(data = ggdat |> filter(x >= 2),\n                 aes(x = x, ymin = 0, ymax = PMF),\n                 color = \"darkorchid2\", linewidth = 2, alpha = 0.5) +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"x\", breaks = 0:3) +\n  ylab(\"Probability\") +\n  theme_bw()\n\nCDF.plot = ggplot() +\n  geom_step(data = ggdat, aes(x = x, y = CDF)) +\n  geom_point(data = ggdat |> filter(x == 1),\n             aes(x = x, y = CDF),\n             color = \"darkorchid2\", size = 2.5, alpha = 0.5) +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"x\", breaks = 0:3) +\n  ylab(\"Cumulative Probability\") +\n  theme_bw()\n\nPMF.plot | CDF.plot\n```\n\n::: {.cell-output-display}\n![Beta-Binomial](Lab8WriteUp_files/figure-pdf/unnamed-chunk-7-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nMy winning probability for the beta-binomial model is ~ 76% compared to the binomial and negative binomial results of ~78%. This discrepancy is most likely due to Player A's varying win probability. \n\n## The Why\nCheck the expected value and variance of each distribution.\n\nAnalytically, we have\n\\begin{align*}\n  E(X) &= np  &&var(X) = np(1-p) \\tag{Binomial Distribution}\\\\\n  E(X) &= n\\left(\\frac{\\alpha}{\\alpha+\\beta}\\right)  &&var(X) = \\frac{n \\alpha \\beta (\\alpha + \\beta + n)}{(\\alpha+\\beta)^2(\\alpha + \\beta + 1)} \\tag{Beta-Binomial Distribution}\n\\end{align*}\n\n**For each distribution, compute the mean number of legs won for player A.**\\\n**Hint**: You can perform the sum over the finite support set here. \n\\begin{align*}\n  E(X)   = \\mu_X    &= \\sum_{i=0}^3 i f_X(i)\\\\\n  var(X) = \\sigma^2_X &= \\sum_{i=0}^3 (i-\\mu_X)^2 f_X(i)\n\\end{align*}\n\n**Solution**\n\n\n \\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn = 3\np = 0.7\n\n#expected binomial value\nE_x_binom = n*p\nE_x_binom\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.1\n```\n\n\n:::\n\n```{.r .cell-code}\n#binomial var\nvar_x_binom = n* p * (1-p)\nvar_x_binom\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.63\n```\n\n\n:::\n\n```{.r .cell-code}\nalpha = 7\nbeta = 3\n\n#expected beta binom value\nE_x_betabinom = n * (alpha/(alpha+beta))\nE_x_betabinom\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.1\n```\n\n\n:::\n\n```{.r .cell-code}\n#beta binom var\nvar_x_betabinom = (n*alpha*beta*(alpha+beta+n))/((alpha+beta)^2*(alpha+beta+1))\nvar_x_betabinom\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7445455\n```\n\n\n:::\n\n```{.r .cell-code}\nx = 0:3\n\nbinom_PMF = dbinom(x = x, size = 3, prob = 0.7)\nbetabinom_PMF = dbbinom(x = x, size = 3, alpha = 7, beta = 3)\n\n#expected\nbinom_mean = sum(x * binom_PMF)\nbinom_mean\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.1\n```\n\n\n:::\n\n```{.r .cell-code}\nbetabinom_mean = sum(x * betabinom_PMF)\nbetabinom_mean\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.1\n```\n\n\n:::\n\n```{.r .cell-code}\n#standard deviation\nbinom_std = sqrt(sum((x - binom_mean)^2 * binom_PMF))\nbinom_std\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7937254\n```\n\n\n:::\n\n```{.r .cell-code}\nbetabinom_std = sqrt(sum((x - betabinom_mean)^2 * betabinom_PMF))\nbetabinom_std\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8628705\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nThe mean number of legs for both the binomial and beta-binomial distribution is 2.1. However, the binomial variance is 0.63, while the beta-binomial variance is higher at 0.74. This is higher variability is because the beta-binomial systems allows the leg-win probability to vary slightly. \n\n\n# Altham's Multiplicative Binomial Distribution\nWhile the Beta-Binomial enables us to model cases where winning has a clustering effect (e.g., a \"hot hand\").\n\n## Probability Mass Function\nThe mass function for this distribution is below. While it used to be available in the `MBD` package for `R`, this package is no longer available.\n$$f_X(x) = \\frac{1}{c} {n \\choose x} p^x (1-p)^{n-x} \\theta^{x(n-x)}I(x \\in \\{0, 1, ..., n\\})$$\nwhere\n$$c = \\sum_{i=0}^n {n \\choose i} p^i (1-p)^{n-i} \\theta^{i(n-i)}$$ \n\n**Write a function in `R` called `daltbinom()` for computing the PMF of this distribution. Use your function to plot the distribution where $p=0.70$ where $\\theta=0.50$, $\\theta=1$, and $\\theta=1.50$. Comment on the differences in the context of a best two-out-of-three match**\n\n**Solution**\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#made my function here\ndaltbinom = function(x, p, theta, n){\n  i = 0:n\n\n  c = sum((choose(n,i))*(p^i)*(1-p)^(n-i)*theta^(i*(n-i)))\n\n  pmf = 1/c * choose(n,x) * p^x * (1-p)^(n-x)*theta^(x*(n-x))\n\n  #use logical for indicator\n  return(pmf * (x %in% i))\n}\n\n#created my data table\nggdat = tibble(\n  x = rep(0:3, times = 3),\n  theta = rep(c(0.5,1,1.5),each = 4)\n) |>\n  mutate(\n    PMF = case_when(\n      theta == 0.5 ~ daltbinom(x=x, p = 0.7, theta = 0.5, n = 3),\n      theta == 1 ~ daltbinom(x = x, p = 0.7, theta = 1, n = 3),\n      theta == 1.5 ~ daltbinom(x=x, p = 0.7, theta = 1.5, n = 3)\n    )\n  )\n\n#plot\nPMF.plot = ggplot() +\n  geom_linerange(data = ggdat,\n                 aes(x = x, ymin = 0, ymax = PMF, color = factor(theta))) +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"x\", breaks = 0:3) +\n  scale_color_discrete(name = expression(theta)) + \n  ylab(\"Probability\") +\n  theme_bw()+\n  facet_wrap(~theta, labeller = label_bquote(theta == .(theta)))\n\nPMF.plot\n```\n\n::: {.cell-output-display}\n![PMF for theta = 0.5, 1, 1.5 and p = 0.7](Lab8WriteUp_files/figure-pdf/unnamed-chunk-9-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nBased on the PMF plot, we see that as we vary theta lower, we get a more 'hot-handed' effect, where you're more likely to win more hands the better you're doing, so we get a clumpy effect. At theta = 1, we get a normal binomial distribution, as we find there to be no effect on the PMF at that number. At higher thetas, we see a less clumpy effect where the number of legs won is more centered around 2, and thus the hot-hand effect has the opposite effect, where wins result in less wins, and it's more weighted towards Player A's leg-win probability, p. Thus, we get more 2-1 games. \n\n## Cumulative Distribution Function\n**Use your `daltbinom()` function to create a `paltbinom()` function for computing the CDF of this distribution. Use your function to plot the distribution where $p=0.70$ where $\\theta=0.50$, $\\theta=1$, and $\\theta=1.50$.**\n\n**Solution**\n\nSince the CDF is just the probability that X is less than or equal to some value, I can compute it by summing the PMF from 0 up to x. \n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npaltbinom = function(x, p, theta, n){\n  sapply(x, function(z){ #applies function for each 0 to z in x\n    sum(daltbinom(x = 0:z, p = p, theta = theta, n = n))}) #sums PMF values from 0 to z\n}\n\n#created my data table\nggdat = tibble(\n  x = rep(0:3, times = 3),\n  theta = rep(c(0.5,1,1.5),each = 4)\n) |>\n  mutate(\n    CDF = case_when(\n      theta == 0.5 ~ paltbinom(x=x, p = 0.7, theta = 0.5, n = 3),\n      theta == 1 ~ paltbinom(x = x, p = 0.7, theta = 1, n = 3),\n      theta == 1.5 ~ paltbinom(x=x, p = 0.7, theta = 1.5, n = 3)\n    )\n  )\n\n#plot\nCDF.plot = ggplot() +\n  geom_step(data = ggdat, aes(x = x, y = CDF)) +\n  geom_point(data = ggdat,\n             aes(x = x, y = CDF),\n             color = \"darkorchid2\", size = 2) +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"x\", breaks = 0:3) +\n  ylab(\"Cumulative Probability\") +\n  theme_bw() +\n  facet_wrap(~factor(theta))\n\nCDF.plot\n```\n\n::: {.cell-output-display}\n![CDF for $\\theta$ = 0.5, 1, 1.5 and p = 0.7](Lab8WriteUp_files/figure-pdf/unnamed-chunk-10-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nBased on the CDF plot we see that changing our theta values affects where the cumulative probability clumps up. At lower $\\theta$ values, probability clumps reflecting the hot-hand effect. Once again, at $\\theta$ = 1, we get a normal binomial distribution. At greater theta values, the clumpy effect is reduced, with more probability at middle values, thus more likely heading to 2-1 outcomes. \n\n## The Winning Probability\n**Compute the probability that Player A wins the match using Altham's Multiplicative Binomial Distribution. Compare your result to the Binomial and Negative Binomial results. Compare your results to the Beta-Binomial model, too. Make sure write out your probability statement and work to write it in terms of the distribution function (PMF/CDF) to plot the probability using `ggplot`.**\n\n**Solution**\n\nOnce again, lets let X be the number of legs Player A wins in a 2-out-of-3 match, where X follows Altham's Multiplicative Binomial Distribution. Since Player A wins the game if they win at least 2 legs, we are looking for $P(X\\geq2)$. This is the same as:\n\n$$P(X\\geq2) = 1 - P(X\\leq1) = 1- F_X(1)$$.\n\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#each theta case here\nwin_prob_0.5 = 1 - paltbinom(x = 1, p = 0.7, theta = 0.5, n = 3)\nwin_prob_0.5\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8592417\n```\n\n\n:::\n\n```{.r .cell-code}\nwin_prob_1 = 1 - paltbinom(x = 1, p = 0.7, theta = 1, n = 3)\nwin_prob_1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.784\n```\n\n\n:::\n\n```{.r .cell-code}\nwin_prob_1.5 = 1 - paltbinom(x = 1, p = 0.7, theta = 1.5, n = 3)\nwin_prob_1.5\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.746993\n```\n\n\n:::\n\n```{.r .cell-code}\nggdat = tibble(\n  x = rep(0:3, times = 3),\n  theta = rep(c(0.5, 1, 1.5), each = 4)\n) |>\n  mutate(\n    PMF = case_when(\n      theta == 0.5 ~ daltbinom(x = x, p = 0.7, theta = 0.5, n = 3),\n      theta == 1 ~ daltbinom(x = x, p = 0.7, theta = 1, n = 3),\n      theta == 1.5 ~ daltbinom(x = x, p = 0.7, theta = 1.5, n = 3)\n    ),\n    CDF = case_when(\n      theta == 0.5 ~ paltbinom(x = x, p = 0.7, theta = 0.5, n = 3),\n      theta == 1 ~ paltbinom(x = x, p = 0.7, theta = 1, n = 3),\n      theta == 1.5 ~ paltbinom(x = x, p = 0.7, theta = 1.5, n = 3)\n    )\n  )\n\nPMF.plot = ggplot() +\n  geom_linerange(data = ggdat,\n                 aes(x = x, ymin = 0, ymax = PMF)) +\n  geom_linerange(data = ggdat |> filter(x >= 2),\n                 aes(x = x, ymin = 0, ymax = PMF),\n                 color = \"darkorchid2\", linewidth = 2, alpha = 0.5) +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"x\", breaks = 0:3) +\n  ylab(\"Probability\") +\n  theme_bw() +\n  facet_wrap(~factor(theta))\n\nCDF.plot = ggplot() +\n  geom_step(data = ggdat, aes(x = x, y = CDF)) +\n  geom_point(data = ggdat |> filter(x == 1),\n             aes(x = x, y = CDF),\n             color = \"darkorchid2\", size = 2.5, alpha = 0.5) +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"x\", breaks = 0:3) +\n  ylab(\"Cumulative Probability\") +\n  theme_bw() +\n  facet_wrap(~factor(theta))\n\nPMF.plot / CDF.plot\n```\n\n::: {.cell-output-display}\n![Altham's Multiplicative Binomial Distribution with $\\theta$ = 0.5, 1, 1.5 and p = 0.7](Lab8WriteUp_files/figure-pdf/unnamed-chunk-11-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nWhen theta is 1, the model gives the same result as in the ordinary binomial distribution. When theta is 0.5, the distribution is more clumpy so it is more likely Player A will win as wins influence more wins, already being influenced by Player A's 70% leg-win chance. When theta is 1.5, distribution is more centerd around the center, thus a greater 2-1 outcome, thus influencing a relatively lower win chance for Player A. \n\nBoth the binomial and negative binomial gave a win probability of 0.784, while the beta-binomial model gave a lower win probability of 0.7636. For Altham's it depends on the theta value used. For lower theta values the win probability is higher than the rest of the models. For higher theta values the win probability is lowered even below all the other models' win probability. Altham's model better models the case where legs have a dependent, not independent, effect on other legs. \n\n# Altham's Multiplicative Beta-Binomial Distribution\nYou may have wondered -- \"Can we do the Beta thing with Altham's version of the Binomial Distribution?\" The answer is yes!\n\n## Probability Mass Function\nThe mass function for this distribution is below. \n$$f_X(x) = \\left[\\int_{0}^1 dp\n\\left(\\frac{1}{c} {n \\choose x} p^x (1-p)^{n-x} \\theta^{x(n-x)}\\right)\\left(\\frac{\\Gamma(\\alpha+\\beta)}{\\Gamma(\\alpha)\\Gamma(\\beta)} p^{\\alpha-1}(1-p)^{\\beta-1}\\right)\\right]I(x \\in \\{0, 1, ..., n\\})$$\n\n**Write a function in `R` called `daltbbinom()` for computing the PMF of this distribution. Use your function to plot the distribution where $\\alpha=7$ and $\\beta=3$ where $\\theta=0.50$, $\\theta=1$, and $\\theta=1.50$. Comment on the differences in the context of a best two-out-of-three match.**\\\n\n**Hint**: You can use the `integrate()` in `R` to compute the integral. Note that this requires the function to be vectorized -- it should be unless you have added any block conditionals. \n\n**Solution**\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndaltbbinom = function(x, alpha, beta, theta, n){\n  #I had an issue because integrate() passes in multiple values of p at once,\n  #so I used a second sapply() to evaluate one p-value at a time\n\n  sapply(x, function(z){ #apply from 0 to z in x\n    f_x = function(p){\n      sapply(p, function(m){ #apply from 0 to m in p \n        daltbinom(x = z, p = m, theta = theta, n = n) * dbeta(m, alpha, beta)\n      })\n    }\n    integrate(f_x, lower = 0, upper = 1)$value\n  })\n}\n\nggdat = tibble(\n  x = rep(0:3, times = 3),\n  theta = rep(c(0.5, 1, 1.5), each = 4)\n) |>\n  mutate(\n    PMF = case_when(\n      theta == 0.5 ~ daltbbinom(x = x, alpha = 7, beta = 3, theta = 0.5, n = 3),\n      theta == 1 ~ daltbbinom(x = x, alpha = 7, beta = 3, theta = 1, n = 3),\n      theta == 1.5 ~ daltbbinom(x = x, alpha = 7, beta = 3, theta = 1.5, n = 3)\n    )\n  )\n\nPMF.plot = ggplot() +\n  geom_linerange(data = ggdat,\n                 aes(x = x, ymin = 0, ymax = PMF),\n                 linewidth = 1, color = \"darkorchid2\") +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"x\", breaks = 0:3) +\n  ylab(\"Probability\") +\n  theme_bw() +\n  facet_wrap(~factor(theta))\n\nPMF.plot\n```\n\n::: {.cell-output-display}\n![PMF for Altham's Multiplicative BB Distribution with theta = 0.5, 1, 1.5, alpha = 7, and beta = 3](Lab8WriteUp_files/figure-pdf/unnamed-chunk-12-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\nWhen theta is 0.5, we see the same clumpy effect towards 3 where Player A is much more likely to win all 3 games. When theta is 1, we reduce back down to the Beta-binomial model. When theta is 1.5, the distribution gets to be less clumpy and more centered around 2 wins, results in 2-1 matches more. \n\n# A Comparison\nCompute the probabilities for all outcomes for Player A.\n\n* Loses 0-2 (LL\"L\", LL\"W\")\n* Loses 1-2 (WLL, LWL)\n* Wins 2-0 (WW\"W\", WW\"L\")\n* Wins 2-1 (LWW, WLW)\n\n**Note**: You'll need to define these outcomes in terms of the random variable. \n\n**Create a bar plot (or column plot) using `ggplot` to show the probability of each outcome under the following conditions:**\n\n* **Binomial**\n* **Negative Binomial**\\\n**Note**: You can compute the lose probabilities the same way as the win probabilities using success probability ($1-p$)\n* **Beta-Binomial**\n* **Althman Binomial with $\\theta=0.50$ and $\\theta=1.5$**\n* **Althman Beta-Binomial with $\\theta=0.50$ and $\\theta=1.5$**\n\n\n\n**Comment on the differences in the context of a best two-out-of-three match.**\n\n**Solution**\n\nI let X be the total number of legs won by Player A out of the three possible leg outcomes, including when the third leg is unplayed. I started with the probability distribution for total wins out of the 3 possible legs, and then split those into the actual match outcomes. Since some three-leg outcomes include cases where the third leg would not actually be played (WWW or WWL), I redistributed those probabilities to match the real results (like we made the table after class) That way I could compare all the models using the exact outcome categories, instead of reordering and making things more convulated. \n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\noutcomes = c(\"Loss: 0-2\", \"Loss: 1-2\", \"Win: 2-0\", \"Win: 2-1\")\nalpha = 7\nbeta = 3\np=0.7\n\n#binomial\nprobs = dbinom(x = 0:3, size = 3, prob = 0.7)\n\nbinom_dat = tibble(\n  outcome = outcomes,\n  prob = c((probs[1]+1/3*probs[2]),2/3*probs[2], probs[4]+1/3*probs[3], 2/3*probs[3]),\n  model = \"Binomial\"\n)\n\n#negative binomial\n#i use 1-p for losses (overall)\n#i use p for wins (overall)\nnbinom_dat = tibble(\n  outcome = outcomes,\n  prob = c(\n    dnbinom(x = 0, size = 2, prob = 1-p),\n    dnbinom(x = 1, size = 2, prob = 1-p),\n    dnbinom(x = 0, size = 2, prob = p),\n    dnbinom(x = 1, size = 2, prob = p)),\n  model = \"Negative Binomial\"\n)\n\n#beta binom\nprobs = dbbinom(x = 0:3, size = 3, alpha = alpha, beta = beta)\n\nbbinom_dat = tibble(\n  outcome = outcomes,\n  prob = c((probs[1]+1/3*probs[2]),2/3*probs[2], probs[4]+1/3*probs[3], 2/3*probs[3]),\n  model = \"Beta-Binomial\"\n)\n\n#altham binomial theta = 0.5\nprobs = daltbinom(x = 0:3, p = p, theta = 0.5, n = 3)\n\naltham05_dat = tibble(\n  outcome = outcomes,\n  prob = c((probs[1]+1/3*probs[2]),2/3*probs[2], probs[4]+1/3*probs[3], 2/3*probs[3]),\n  model = \"Altham Binomial (theta = 0.5)\"\n)\n\n#altham binomial theta = 1.5\nprobs = daltbinom(x = 0:3, p = p, theta = 1.5, n = 3)\n\naltham15_dat = tibble(\n  outcome = outcomes,\n  prob = c((probs[1]+1/3*probs[2]),2/3*probs[2], probs[4]+1/3*probs[3], 2/3*probs[3]),\n  model = \"Altham Binomial (theta = 1.5)\"\n)\n\n#altham beta-binomial theta = 0.5\nprobs = daltbbinom(x = 0:3, alpha = alpha, beta = beta, theta = 0.5, n = 3)\n\nalthambb05_dat = tibble(\n  outcome = outcomes,\n  prob = c((probs[1]+1/3*probs[2]),2/3*probs[2], probs[4]+1/3*probs[3], 2/3*probs[3]),\n  model = \"Altham Beta-Binomial (theta = 0.5)\"\n)\n\n#altham beta-binomial theta = 1.5\nprobs = daltbbinom(x = 0:3, alpha = alpha, beta = beta, theta = 1.5, n = 3)\n\nalthambb15_dat = tibble(\n  outcome = outcomes,\n  prob = c((probs[1]+1/3*probs[2]),2/3*probs[2], probs[4]+1/3*probs[3], 2/3*probs[3]),\n  model = \"Altham Beta-Binomial (theta = 1.5)\"\n)\n\n#put together\nggdat = bind_rows( #had to look this up, i forgar\n  binom_dat,\n  nbinom_dat,\n  bbinom_dat,\n  altham05_dat,\n  altham15_dat,\n  althambb05_dat,\n  althambb15_dat\n)\n\nggplot(ggdat, aes(x = outcome, y = prob, fill = outcome)) +\n  geom_col() +\n  facet_wrap(~model) +\n  ylab(\"Probability\") +\n  xlab(\"Outcomes\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Probabilities for outcomes across models](Lab8WriteUp_files/figure-pdf/unnamed-chunk-13-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nThe binomial model assumes a fixed leg-win probability of 0.7. So we see a higher trend to 2 and 3 wins. In fact, in all the models it is most probable that Player A's record is 2-0 in the game. The negative binomial shows the same idea. The beta-binomial is similar but allows the leg-win probability to vary very slightly to adjust for more realistic variations. The Altham Binomial models show how clumping affects the overall outcome. With lower thetas, wins stack and clump together, creating more 2-0 or 0-2 chances, while the opposite is true for higher thetas, creating more 2-1 or 1-2 chances. Combining the Altham with the Beta Binomial we get the combination of leg dependency and variations in leg-win probability. Overall, each model does better with different scenarios. The Altham Beta-Binomial model does well to show hot-hand behavior with varying performance through a match. But, depending on environment and set up, each model will better illustrate those varying systems. \n\n\n",
    "supporting": [
      "Lab8WriteUp_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}